language: minimal
script: ./funds besdata
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - ./push.sh

branches:
  only:
  - master
